- name: "task to update the packages"
  become: true
  apt:
    upgrade: "yes"

- name: "remove dependencies that are no longer required"
  become: true
  apt:
    autoremove: yes

- name: "install node packages"
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "Install zip utility."
  become: true
  apt:
    name: [ "zip", "unzip" ]
    state: latest
    update_cache: yes

- name: "install nodejs 13.8.0"
  become: true
  shell: n 13.8.0

- name: "install pm2 package"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

  environment:
    ENVIRONMENT: production
    NODE_ENV: production
    TYPEORM_CONNECTION: "{{ lookup('env','TYPEORM_CONNECTION') }}"
    TYPEORM_HOST: "{{ lookup('env','TYPEORM_HOST') }}"
    TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
    TYPEORM_USERNAME: "{{ lookup('env','TYPEORM_USERNAME') }}"
    TYPEORM_PASSWORD: "{{ lookup('env','TYPEORM_PASSWORD') }}"
    TYPEORM_DATABASE: "{{ lookup('env','TYPEORM_DATABASE') }}"
    TYPEORM_MIGRATIONS_DIR: ./src/migrations
    TYPEORM_MIGRATIONS: ./src/migrations/*.ts
    TYPEORM_ENTITIES: ./src/modules/domain/**/*.entity.ts