- name: "task to update the packages"
  become: true
  apt:
    upgrade: "yes"

- name: "remove dependencies that are no longer required"
  apt:
    autoremove: yes

- name: "install node packages"
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "Install zip utility."
  apt:
    name: [ "zip", "unzip" ]
    state: latest
    update_cache: yes

- name: "install pm2 package"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present